name: Collect Projects

on: [push, pull_request]

jobs:
  find-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find project directories containing .sln files
        id: find-projects
        run: |
          # Initialize an empty array for projects
          projects=()

          # Loop through each directory and check for .sln files
          for dir in */; do
            if ls "${dir}"*.sln 1> /dev/null 2>&1; then
              projects+=("$dir")
            fi
          done

          # Print the projects to the console
          echo "Projects found: ${projects[@]}"

          # Save the projects as a single string in an environment variable
          echo "PROJECTS=${projects[*]}" >> $GITHUB_ENV

      - name: Use the array of projects
        run: |
          echo "Array of projects:"
          IFS=' ' read -r -a projects_array <<< "$PROJECTS"
          for project in "${projects_array[@]}"; do
            echo "$project"
            # You can add additional commands to operate on each project here
          done
